{
  "formatVersion": "1.1",
  "component": {
    "group": "team.lodestar.lodestone",
    "module": "lodestone",
    "version": "1.21.1-1.7.0.7-fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-world",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "accessors",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "lazy_registration",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_data",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "lodestone-1.21.1-1.7.0.7-fabric.jar",
          "url": "lodestone-1.21.1-1.7.0.7-fabric.jar",
          "size": 9691703,
          "sha512": "36a2b81bd87b0195e109bca7e04ef91c196fd356340c659f3a0ee900714cb2f6de703f77862c41a2e22707af4bb9c720ad17f227f05e5957df5108f8a5d7538a",
          "sha256": "988b882c5fcfaa1de5e95d57c6cc3e39e15e6c1fcca2b8cb743f218ce099ce52",
          "sha1": "a29cad38bc55f2aa1a4d169ddbac50a7b3dc5016",
          "md5": "c428ab83055f5b52949c95b756e5902c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bawnorton.mixinsquared",
          "module": "mixinsquared-fabric",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.10.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "dev.onyxstudios.cardinal-components-api",
          "module": "cardinal-components-world",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "accessors",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "blocks",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "lazy_registration",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_data",
          "version": {
            "requires": "3.1.0-beta.47+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.108.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "lodestone-1.21.1-1.7.0.7-fabric.jar",
          "url": "lodestone-1.21.1-1.7.0.7-fabric.jar",
          "size": 9691703,
          "sha512": "36a2b81bd87b0195e109bca7e04ef91c196fd356340c659f3a0ee900714cb2f6de703f77862c41a2e22707af4bb9c720ad17f227f05e5957df5108f8a5d7538a",
          "sha256": "988b882c5fcfaa1de5e95d57c6cc3e39e15e6c1fcca2b8cb743f218ce099ce52",
          "sha1": "a29cad38bc55f2aa1a4d169ddbac50a7b3dc5016",
          "md5": "c428ab83055f5b52949c95b756e5902c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lodestone-1.21.1-1.7.0.7-fabric-sources.jar",
          "url": "lodestone-1.21.1-1.7.0.7-fabric-sources.jar",
          "size": 348147,
          "sha512": "9ede33f8b87c2d4387ad85875a3ba3626d4a3dd4bf4255f538d495c96ab6a6396dc667b0ef5f8634f8ce9c5f6da3ffb8e55f338d2f84b2a0a8b9ed0c4f7ca146",
          "sha256": "d74fd066f93ff46f1cb01281fba8c9a7d09fe68a26347f085f09435681684b7a",
          "sha1": "3694d45d6ae4532ff7ed758a65defd4278e4fe48",
          "md5": "8ffc8a44fada670e05f8e9e48e7a9506"
        }
      ]
    }
  ]
}
